# Generated by Django 4.2 on 2023-04-15 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rest_framework.utils.encoders
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cycling_org", "0058_organization_membership_open_raceresult_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalOrganizationMember",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_master_admin", models.BooleanField(default=False)),
                (
                    "membership_price",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "membership_plan",
                    models.JSONField(
                        blank=True,
                        editable=False,
                        encoder=rest_framework.utils.encoders.JSONEncoder,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, null=True)),
                (
                    "org_member_uid",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("start_date", models.DateField(null=True)),
                ("exp_date", models.DateField(null=True)),
                (
                    "member_fields",
                    models.JSONField(
                        blank=True,
                        encoder=rest_framework.utils.encoders.JSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accept", "Accept"),
                            ("reject", "Reject"),
                            ("waiting", "Waiting"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("datetime", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cycling_org.member",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="cycling_org.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical organization member",
                "verbose_name_plural": "historical organization members",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
