# Generated by Django 4.2 on 2023-04-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cycling_org", "0059_historicalorganizationmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="approved",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
