# Generated by Django 4.2 on 2023-04-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cycling_org", "0060_event_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="approved",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
