# Generated by Django 4.1.4 on 2023-02-25 18:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('criteria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('layout', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Event')])),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.criteria')),
            ],
        ),
    ]
