# Generated by Django 4.1.4 on 2023-02-25 18:45

from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='criteria',
            field=models.JSONField(blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='formsmodel',
            name='layout',
            field=models.JSONField(blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True),
        ),
    ]
